name: CrimsonCompass CI/CD Pipeline

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build the package
        run: mvn -B clean package -DskipTests

      - name: Run unit tests
        run: mvn -B -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Set repository owner in lowercase
        run: echo "REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push the image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/crimsoncompass:latest -f Dockerfile .
          docker push ghcr.io/${{ env.REPO_OWNER }}/crimsoncompass:latest


      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'ccmain'
            publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
            images: 'ghcr.io/${{ env.REPO_OWNER }}/crimsoncompass:latest'
      

